# Generated by Django 5.1.2 on 2025-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='AAAAA', editable=False, max_length=5, unique=True),
        ),
    ]
