# Generated by Django 5.1.2 on 2024-10-24 13:17

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_motorcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='motorcycle',
            field=models.ForeignKey(default=booking.models.get_default_motorcycle, on_delete=django.db.models.deletion.CASCADE, to='booking.motorcycle'),
        ),
    ]
