# Generated by Django 5.1.2 on 2025-03-19 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_done',
            field=models.BooleanField(default=False, verbose_name='Payment Done'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
