# Generated by Django 5.1.2 on 2024-10-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_motorcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.motorcycle'),
        ),
    ]
