# Generated by Django 5.1.2 on 2025-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_payment_done_alter_booking_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_3_to_6_days', models.FloatField(default=0.9, verbose_name='3–6 days ratio')),
                ('discount_7_or_more_days', models.FloatField(default=0.8, verbose_name='7+ days ratio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Discount Config',
                'verbose_name_plural': 'Booking Discount Configs',
            },
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='booking_end_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_start_date',
            field=models.DateField(default="2024-07-08"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Total Price (SEK)'),
        ),
    ]
