# Generated by Django 5.1.2 on 2024-10-24 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_service_alter_booking_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='dropoff_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
