# Generated by Django 5.1.2 on 2024-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_name_booking_first_name_booking_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
