# Generated by Django 5.1.2 on 2024-11-01 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='price_practise_1d',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='price_rent_1d',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='price_test',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
