# Generated by Django 5.1.2 on 2024-11-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_motorcycle_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='price_practise_1d',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='price_rent_1d',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='price_test',
            field=models.IntegerField(default=0),
        ),
    ]
