# Generated by Django 5.1.2 on 2024-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Dåligt'), (2, '2 - Inte bra'), (3, '3 - Okej'), (4, '4 - Bra'), (5, '5 - Utmärkt')]),
        ),
    ]
