# Generated by Django 5.1.2 on 2024-11-01 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_review_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='review',
            name='last_name',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='motorcycle',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.motorcycle'),
            preserve_default=False,
        ),
    ]
